/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BookmarksImport } from './routes/_bookmarks'
import { Route as BookmarksBookmarksCategoryImport } from './routes/_bookmarks/bookmarks/$category'

// Create Virtual Routes

const SignUpLazyImport = createFileRoute('/sign-up')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const BookmarksBookmarksIndexLazyImport = createFileRoute(
  '/_bookmarks/bookmarks/',
)()

// Create/Update Routes

const SignUpLazyRoute = SignUpLazyImport.update({
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-up.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const BookmarksRoute = BookmarksImport.update({
  id: '/_bookmarks',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BookmarksBookmarksIndexLazyRoute =
  BookmarksBookmarksIndexLazyImport.update({
    path: '/bookmarks/',
    getParentRoute: () => BookmarksRoute,
  } as any).lazy(() =>
    import('./routes/_bookmarks/bookmarks/index.lazy').then((d) => d.Route),
  )

const BookmarksBookmarksCategoryRoute = BookmarksBookmarksCategoryImport.update(
  {
    path: '/bookmarks/$category',
    getParentRoute: () => BookmarksRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_bookmarks': {
      id: '/_bookmarks'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BookmarksImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/_bookmarks/bookmarks/$category': {
      id: '/_bookmarks/bookmarks/$category'
      path: '/bookmarks/$category'
      fullPath: '/bookmarks/$category'
      preLoaderRoute: typeof BookmarksBookmarksCategoryImport
      parentRoute: typeof BookmarksImport
    }
    '/_bookmarks/bookmarks/': {
      id: '/_bookmarks/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksBookmarksIndexLazyImport
      parentRoute: typeof BookmarksImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BookmarksRoute: BookmarksRoute.addChildren({
    BookmarksBookmarksCategoryRoute,
    BookmarksBookmarksIndexLazyRoute,
  }),
  LoginLazyRoute,
  SignUpLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_bookmarks",
        "/login",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_bookmarks": {
      "filePath": "_bookmarks.tsx",
      "children": [
        "/_bookmarks/bookmarks/$category",
        "/_bookmarks/bookmarks/"
      ]
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.lazy.tsx"
    },
    "/_bookmarks/bookmarks/$category": {
      "filePath": "_bookmarks/bookmarks/$category.tsx",
      "parent": "/_bookmarks"
    },
    "/_bookmarks/bookmarks/": {
      "filePath": "_bookmarks/bookmarks/index.lazy.tsx",
      "parent": "/_bookmarks"
    }
  }
}
ROUTE_MANIFEST_END */
